const TWSE_CLOSE='https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL';
const TPEX_CLOSE='https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes';
const TPEX_ALL='https://www.tpex.org.tw/openapi/v1/tpex_mainboard_quotes';
const V13_APP='https://project-u1e4.hatchable.site/app.js';
const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'Content-Type'};
const n=v=>{if(v==null)return null;const x=Number(String(v).replaceAll(',','').replace(/[^\d.-]/g,''));return Number.isFinite(x)?x:null};
const pick=(o,ks)=>{for(const k of ks)if(o?.[k]!=null&&o[k]!=='')return o[k];return null};
async function jf(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${r.status} ${url}`);return r.json()}
function json(data,cache='public, max-age=15'){return new Response(JSON.stringify(data),{headers:{...CORS,'content-type':'application/json; charset=utf-8','cache-control':cache}})}
function parseClose(o,market){const code=String(pick(o,['Code','SecuritiesCompanyCode'])||'').trim();if(!/^\d{4}$/.test(code))return null;return{code,name:String(pick(o,['Name','CompanyName','SecuritiesCompanyName'])||code).trim(),close:n(pick(o,['ClosingPrice','Close','ClosePrice'])),change:n(pick(o,['Change','ChangeAmount'])),value:n(pick(o,['TradeValue','TransactionAmount','TransactionValue','Amount'])),date:String(pick(o,['Date','TradeDate'])||''),market,source:'最近收盤'}}
function marketOpen(){const d=new Date(Date.now()+8*3600e3),day=d.getUTCDay(),m=d.getUTCHours()*60+d.getUTCMinutes();return day>=1&&day<=5&&m>=525&&m<=845}
async function quotes(){const [a,b]=await Promise.allSettled([jf(TWSE_CLOSE),jf(TPEX_CLOSE)]),out={};if(a.status==='fulfilled')for(const o of a.value){const q=parseClose(o,'tse');if(q)out[q.code]=q}if(b.status==='fulfilled')for(const o of b.value){const q=parseClose(o,'otc');if(q)out[q.code]=q}if(marketOpen()){const requested=Object.keys(out);for(let i=0;i<requested.length;i+=80){const batch=requested.slice(i,i+80),ex=batch.map(c=>`${out[c].market}_${c}.tw`).join('|');try{const j=await jf('https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch='+encodeURIComponent(ex)+'&json=1&delay=0');for(const x of j.msgArray||[]){const code=String(x.c||'').trim();if(!out[code])continue;const z=n(x.z),tz=n(x.trade?.z),p=z??tz,y=n(x.y),v=n(x.v),value=v!=null&&p!=null?v*1000*p:null;if(p!=null||v!=null)out[code]={...out[code],close:p??out[code].close,change:p!=null&&y!=null?p-y:out[code].change,value:value??out[code].value,source:'盤中',time:x.trade?.t||x.t||'',date:x.d||out[code].date}}}catch{}}}return json({ok:true,updated:new Date().toISOString(),quotes:out},marketOpen()?'public, max-age=12':'public, max-age=300')}
function date8(v){const p=String(v||'').trim().split('/');if(p.length!==3)return null;let y=Number(p[0]);if(y<1911)y+=1911;return `${y}${p[1].padStart(2,'0')}${p[2].padStart(2,'0')}`}
function twNow(){return new Date(Date.now()+8*3600e3)}
function months(){const d=twNow(),y=d.getUTCFullYear(),m=d.getUTCMonth()+1,prev=new Date(Date.UTC(y,m-2,1));return[`${prev.getUTCFullYear()}${String(prev.getUTCMonth()+1).padStart(2,'0')}01`,`${y}${String(m).padStart(2,'0')}01`]}
async function twseHist(code){let all=[];for(const date of months()){try{const j=await jf(`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${date}&stockNo=${code}&response=json`);if(j.stat==='OK')all.push(...j.data.map(r=>({date:date8(r[0]),value:n(r[2]),market:'tse'})))}catch{}}return all.filter(x=>x.date&&x.value!=null).sort((a,b)=>a.date.localeCompare(b.date)).slice(-12)}
async function tpexHist(code){const d=twNow(),dates=[new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()-1,1)),d],all=[];for(const z of dates){const date=`${z.getUTCFullYear()}/${String(z.getUTCMonth()+1).padStart(2,'0')}/01`;try{const j=await jf(`https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock?code=${code}&date=${date}&id=&response=json`);for(const r of (j.tables||[]).flatMap(t=>t.data||[])){const v=n(r[2]);if(v!=null)all.push({date:date8(r[0]),value:v*1000,market:'otc'})}}catch{}}return all.filter(x=>x.date&&x.value!=null).sort((a,b)=>a.date.localeCompare(b.date)).slice(-12)}
async function history(url){const codes=[...new Set((url.searchParams.get('codes')||'').split(',').filter(x=>/^\d{4}$/.test(x)))].slice(0,80);const [ta,oa]=await Promise.all([jf(TWSE_CLOSE),jf(TPEX_ALL)]),tse=new Set((ta||[]).map(x=>String(x.Code||'').trim())),otc=new Set((oa||[]).map(x=>String(x.SecuritiesCompanyCode||'').trim())),values={};for(let i=0;i<codes.length;i+=16)await Promise.all(codes.slice(i,i+16).map(async c=>{try{values[c]=tse.has(c)?await twseHist(c):otc.has(c)?await tpexHist(c):[]}catch{values[c]=[]}}));return json({ok:true,unit:'TWD',values},'public, max-age=43200')}
async function cached(request,ttl,fn,keyUrl){const cache=caches.default,key=new Request(keyUrl||request.url,{method:'GET'}),hit=await cache.match(key);if(hit)return hit;const r=await fn();if(r.ok){const h=new Headers(r.headers);h.set('cache-control',`public, max-age=${ttl}`);const c=new Response(r.body,{status:r.status,headers:h});await cache.put(key,c.clone());return c}return r}
async function fullV13App(){const cache=caches.default,key=new Request('https://tim-sector-ranking.internal/full-v13-app-fast-v2.js');const hit=await cache.match(key);if(hit)return hit;const r=await fetch(V13_APP);if(!r.ok)return new Response('// mapping source unavailable',{status:502});let text=await r.text();text=text.replace("const HCACHE='sector-history-v8-correct-tpex';","const HCACHE='sector-history-cloudflare-v2';");text=text.replace('for(let i=0;i<codes.length;i+=20)batches.push(codes.slice(i,i+20))','for(let i=0;i<codes.length;i+=80)batches.push(codes.slice(i,i+80))');text=text.replace('Math.min(6,batches.length)','Math.min(4,batches.length)');text=text.replace("fetch(api+'/history?codes='+batch.join(','),{cache:'no-store'})","fetch(api+'/history?codes='+batch.join(','))");const out=new Response(text,{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=86400'}});await cache.put(key,out.clone());return out}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:CORS});const u=new URL(request.url);try{if(u.pathname==='/app.js')return await fullV13App();if(u.pathname==='/api/quotes')return await cached(request,marketOpen()?12:300,quotes,`${u.origin}/api/quotes`);if(u.pathname==='/api/history')return await cached(request,43200,()=>history(u));return env.ASSETS.fetch(request)}catch(e){return json({ok:false,error:String(e)},'no-store')}}};
