const TWSE_CLOSE='https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL';
const TPEX_CLOSE='https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes';
const CORS={'access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'Content-Type'};
const n=v=>{if(v==null)return null;const s=String(v).trim();if(!s||s==='-'||s==='--')return null;const x=Number(s.replaceAll(',','').replace(/[^\d.-]/g,''));return Number.isFinite(x)?x:null};
const pick=(o,ks)=>{for(const k of ks)if(o?.[k]!=null&&o[k]!=='')return o[k];return null};
async function jf(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0','accept':'application/json,text/plain,*/*'},cf:{cacheTtl:0}});if(!r.ok)throw Error(`${r.status} ${url}`);return r.json()}
function json(data,cache='public, max-age=15'){return new Response(JSON.stringify(data),{headers:{...CORS,'content-type':'application/json; charset=utf-8','cache-control':cache}})}
function normDate(v){const s=String(v||'').replace(/[^0-9]/g,'');if(s.length===8)return s;if(s.length===7)return String(Number(s.slice(0,3))+1911)+s.slice(3);return s}
function tw(){return new Date(Date.now()+8*3600e3)}
function mins(){const d=tw();return d.getUTCHours()*60+d.getUTCMinutes()}
function weekday(){const x=tw().getUTCDay();return x>=1&&x<=5}
function marketOpen(){const m=mins();return weekday()&&m>=540&&m<=810}
function useMis(){const m=mins();return weekday()&&m>=525&&m<=1200}
function today8(){const d=tw();return `${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`}
function parseClose(o,market){const code=String(pick(o,['Code','SecuritiesCompanyCode','SecuritiesCompanyCode'])||'').trim();if(!/^\d{4}$/.test(code))return null;let value=n(pick(o,['TradeValue','TransactionAmount','TransactionValue','Amount']));const volume=n(pick(o,['TradeVolume','TradingShares','TradingVolume']));if(value==null&&volume===0)value=0;if(value==null&&volume==null)value=0;return{code,name:String(pick(o,['Name','CompanyName','SecuritiesCompanyName'])||code).trim(),close:n(pick(o,['ClosingPrice','Close','ClosePrice'])),change:n(pick(o,['Change','ChangeAmount'])),value,volume,date:normDate(pick(o,['Date','TradeDate'])),market,source:'最近收盤'}}
async function tpexFallback(c){try{const j=await jf('https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock?code='+c+'&date='+encodeURIComponent(slashDate(today8()))+'&id=&response=json');for(const t of j.tables||[]){const fields=t.fields||[];const ci=fieldIndex(fields,/代號/),ni=fieldIndex(fields,/名稱/),pi=fieldIndex(fields,/收盤/),vi=fieldIndex(fields,/成交金額/),qi=fieldIndex(fields,/成交股數|成交量/);for(const r of t.data||[]){const rc=ci>=0?String(r[ci]||'').trim():c;if(rc!==c)continue;const p=pi>=0?n(r[pi]):null,q=qi>=0?n(r[qi]):null;let value=vi>=0?n(r[vi]):null;if(value==null&&q!=null&&p!=null)value=q*p;if(p!=null)return{code:c,name:ni>=0?String(r[ni]||c).trim():c,close:p,volume:q,value,date:today8(),market:'otc',source:'櫃買官方'}}}}catch{}return null}
async function yahooFallback(c){for(const suffix of ['.TWO','.TW']){try{const r=await fetch('https://query1.finance.yahoo.com/v7/finance/quote?symbols='+encodeURIComponent(c+suffix),{headers:{'user-agent':'Mozilla/5.0','accept':'application/json'}});if(!r.ok)continue;const x=(await r.json())?.quoteResponse?.result?.[0];if(!x)continue;const p=n(x.regularMarketPrice),v=n(x.regularMarketVolume);if(p==null)continue;return{name:String(x.shortName||x.longName||c),close:p,volume:v,value:v!=null?v*p:null,date:today8(),market:suffix==='.TWO'?'otc':'tse',source:'Yahoo備援'}}catch{}}return null}
async function quotes(url){const [a,b]=await Promise.allSettled([jf(TWSE_CLOSE),jf(TPEX_CLOSE)]),out={};if(a.status==='fulfilled')for(const o of a.value){const q=parseClose(o,'tse');if(q)out[q.code]=q}if(b.status==='fulfilled')for(const o of b.value){const q=parseClose(o,'otc');if(q)out[q.code]=q}let requested=[...new Set((url.searchParams.get('codes')||'').split(',').filter(x=>/^\d{4}$/.test(x)))];if(!requested.length)requested=Object.keys(out);if(useMis()){const today=today8(),batches=[];for(let i=0;i<requested.length;i+=80)batches.push(requested.slice(i,i+80));for(let w=0;w<batches.length;w+=6){const rr=await Promise.allSettled(batches.slice(w,w+6).map(async batch=>jf('https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch='+encodeURIComponent(batch.flatMap(c=>out[c]?[`${out[c].market}_${c}.tw`]:[`otc_${c}.tw`,`tse_${c}.tw`]).join('|'))+'&json=1&delay=0&_='+Date.now()+Math.random())));for(const r of rr)if(r.status==='fulfilled')for(const x of r.value.msgArray||[]){const c=String(x.c||''),d=normDate(x.d),p=n(x.z)??n(x.trade?.z)??n(x.pz),y=n(x.y),v=n(x.v);if(d===today&&(p!=null||v!=null)){const base=out[c]||{code:c,name:String(x.n||c),market:String(x.ex||'').toLowerCase()==='otc'?'otc':'tse',value:null,close:null,change:null};out[c]={...base,name:String(x.n||base.name||c),close:p??base.close,change:p!=null&&y!=null?p-y:base.change,value:v!=null&&p!=null?v*1000*p:base.value,volume:v!=null?v*1000:base.volume,date:d,source:marketOpen()?'盤中':'今日收盤',time:x.trade?.t||x.t||''}}}}const missing=requested.filter(c=>!out[c]||out[c].close==null||out[c].value==null);for(let i=0;i<missing.length;i+=8){const rr=await Promise.all(missing.slice(i,i+8).map(async c=>[c,await tpexFallback(c)??await yahooFallback(c)]));for(const [c,y] of rr)if(y)out[c]={...(out[c]||{code:c,market:'yahoo'}),...y,code:c}}}return json({ok:true,updated:new Date().toISOString(),quotes:out},useMis()?'no-store':'public, max-age=300')}
function isoDate(d){return `${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}`}
function slashDate(s){return `${s.slice(0,4)}/${s.slice(4,6)}/${s.slice(6,8)}`}
function candidateDates(){const a=[],d=tw();for(let i=1;i<=24;i++){const x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()-i)),day=x.getUTCDay();if(day!==0&&day!==6)a.push(isoDate(x))}return a.slice(0,16)}
function fieldIndex(f,re){return f.findIndex(x=>re.test(String(x)))}
function parseTwseDay(j,date,want){const out={};for(const t of j.tables||[]){const f=t.fields||[],ci=fieldIndex(f,/證券代號/),vi=fieldIndex(f,/成交金額/),qi=fieldIndex(f,/成交股數/),pi=fieldIndex(f,/收盤價/);if(ci<0)continue;for(const r of t.data||[]){const c=String(r[ci]||'').trim();if(!want.has(c))continue;let v=vi>=0?n(r[vi]):null,estimated=false;if(v==null&&qi>=0&&pi>=0){const q=n(r[qi]),p=n(r[pi]);if(q!=null&&p!=null){v=q*p;estimated=true}}if(v!=null)out[c]={date,value:v,market:'tse',estimated};}if(Object.keys(out).length)break;}return out}
function parseTpexDay(j,date,want){const out={};for(const t of j.tables||[]){const f=t.fields||[],ci=fieldIndex(f,/代號/),vi=fieldIndex(f,/成交金額/),qi=fieldIndex(f,/成交股數|成交量/),pi=fieldIndex(f,/收盤/);if(ci<0)continue;for(const r of t.data||[]){const c=String(r[ci]||'').trim();if(!want.has(c))continue;let v=vi>=0?n(r[vi]):null,estimated=false;if(v!=null)v*=1000;else if(qi>=0&&pi>=0){const q=n(r[qi]),p=n(r[pi]);if(q!=null&&p!=null){v=q*1000*p;estimated=true}}if(v!=null)out[c]={date,value:v,market:'otc',estimated}}}return out}
async function fallbackStock(c,date,market){try{if(market==='tse'){const j=await jf(`https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date=${date.slice(0,6)}01&stockNo=${c}&response=json`);for(const r of j.data||[]){if(normDate(r[0])!==date)continue;let v=n(r[2]),estimated=false;if(v==null){const q=n(r[1]),p=n(r[6]);if(q!=null&&p!=null){v=q*p;estimated=true}}if(v!=null)return{date,value:v,market,estimated}}}else{const j=await jf(`https://www.tpex.org.tw/www/zh-tw/afterTrading/tradingStock?code=${c}&date=${encodeURIComponent(slashDate(date))}&id=&response=json`);for(const t of j.tables||[]){for(const r of t.data||[]){if(normDate(r[0])!==date)continue;let v=n(r[2]),estimated=false;if(v!=null)v*=1000;else{const q=n(r[1]),p=n(r[6]);if(q!=null&&p!=null){v=q*1000*p;estimated=true}}if(v!=null)return{date,value:v,market,estimated}}}}}catch{}return null}
async function historySnapshot(url){const codes=[...new Set((url.searchParams.get('codes')||'').split(',').filter(x=>/^\d{4}$/.test(x)))].sort(),want=new Set(codes),values=Object.fromEntries(codes.map(c=>[c,[]])),dates=candidateDates();let good=[];for(let i=0;i<dates.length&&good.length<10;i+=2){const group=dates.slice(i,i+2),rs=await Promise.all(group.map(async d=>({d,r:await Promise.allSettled([jf(`https://www.twse.com.tw/rwd/zh/afterTrading/MI_INDEX?date=${d}&type=ALLBUT0999&response=json`),jf(`https://www.tpex.org.tw/www/zh-tw/afterTrading/dailyQuotes?date=${encodeURIComponent(slashDate(d))}&response=json`)])})));for(const {d,r} of rs){let day={};if(r[0].status==='fulfilled')Object.assign(day,parseTwseDay(r[0].value,d,want));if(r[1].status==='fulfilled')Object.assign(day,parseTpexDay(r[1].value,d,want));if(Object.keys(day).length){good.push(d);for(const [c,x] of Object.entries(day))values[c].push(x)}}}good=good.sort().slice(-10);for(const c of codes)values[c]=values[c].filter(x=>good.includes(x.date)).sort((a,b)=>a.date.localeCompare(b.date));const missing=[];for(const d of good)for(const c of codes)if(!values[c].some(x=>x.date===d))missing.push({c,d});for(let i=0;i<missing.length;i+=12){const rr=await Promise.allSettled(missing.slice(i,i+12).map(async x=>({x,v:await fallbackStock(x.c,x.d,'tse')??await fallbackStock(x.c,x.d,'otc')})));for(const r of rr)if(r.status==='fulfilled'&&r.value.v)values[r.value.x.c].push(r.value.v)}for(const c of codes)values[c].sort((a,b)=>a.date.localeCompare(b.date));const covered=Object.values(values).filter(a=>a.length).length,estimated=Object.values(values).flat().filter(x=>x.estimated).length;return json({ok:true,mode:'complete-history-v17',dates:good,covered,total:codes.length,estimated,values},'public, max-age=21600')}
async function cached(request,fn){const cache=caches.default,hit=await cache.match(request);if(hit)return hit;const r=await fn();if(r.ok)await cache.put(request,r.clone());return r}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{headers:CORS});const u=new URL(request.url);try{if(u.pathname==='/api/quotes')return useMis()?quotes(u):cached(request,()=>quotes(u));if(u.pathname==='/api/debug-tpex'){const data=await jf(TPEX_CLOSE),codes=(u.searchParams.get('codes')||'5347,3707,3372,3680,3131,6147,3259').split(',');return json({count:data.length,fields:data[0]?Object.keys(data[0]):[],matches:data.filter(x=>codes.includes(String(x.SecuritiesCompanyCode||x.Code||'').trim()))},'no-store')}if(u.pathname==='/api/history'||u.pathname==='/api/history-snapshot')return cached(request,()=>historySnapshot(u));return env.ASSETS.fetch(request)}catch(e){return json({ok:false,error:String(e)},'no-store')}}};